version: '3'
services:
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - '5000:5000'
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - '4200:4200'
